### ISSUE TITLE
Calendar Config Var's Are Obsolete 

### ISSUE THREAD

**Issue by mdmullendore** [WhatSock/bootstrap#11]
### Summary

I noticing that some of the Calendar config variables are not being set when initializing the calendar with `setCalendar`. Min Date in-particular has no effect. 

Sample snippet of config vars and setCalendar

![Screen Shot 2019-08-08 at 4 54 49 PM](https://user-images.githubusercontent.com/8801287/62742927-bbcab800-b9fd-11e9-8472-069098c1ec8c.png)

Previous dates will not be disabled.

**Comment by mdmullendore** [comment]
This is a versioning issue. The NPM version is 1.0.0 - https://www.npmjs.com/package/accdc-bootstrap

**Comment by accdc** [comment]
Hi,
I'm sorry it took so long for me to get back, I've been swamped with other projects lately.

I didn't even realize there was an NPM version of this out there, that is so weird. I'll need to look into whatever process they use for updating projects from GitHub, which is the only place where I post new updates to.

Please let me know if you encounter any other issues, and I'll look into them.

All the best,
Bryan
