### ISSUE TITLE
can't close datepicker with mouse except by selecting a date

### ISSUE THREAD

**Issue by jasonkiss** [WhatSock/bootstrap#3]
Working with the example at http://whatsock.com/bootstrap/, one can easily close the datepicker using the keyboard without having to select a date simply by using the Esc key. But if I open the datepicker with a mouse click, the only way to dismiss it is by actually selecting a date. I would expect to be able to close the datepicker by clicking a mouse anywhere outside the datepicker. 

Update: I realise I probably should have filed this issue at the root accdc level since it applies to all versions. Sorry about that.

**Comment by accdc** [comment]
No problem, thanks :) I hadn't thought of that. This will be easy to add, I'll queue this up to be fixed soon. Please let me know if you encounter anything else!

**Comment by accdc** [comment]
Hi, I've pushed the update to the Calendar Module within all relevant Git projects and on the live sites so it should now work as expected everywhere. Clicking outside of the datepicker will now close it. Please reopen the bug if you notice any holdover issues. :)
