### ISSUE TITLE
Where is the data grid module?

### ISSUE THREAD

**Issue by mmikitka** [WhatSock/bootstrap#5]
Firstly, well done on this module. This is a very generous contribution.

I'm working on an accessible data grid, I [read the technical documentation](http://whatsock.com/tsg/), and [interacted with the example in the coding arena](http://whatsock.com/tsg/Coding%20Arena/ARIA%20Data%20Grids/ARIA%20Data%20Grid%20%28Dynamic%29/demo.htm), but I cannot find the aria_data_grid_module.min.js file in any of the bootstrap repositories.

Is there a reason for excluding this module from the Git repo? If so, any objections to using the module JS file from the coding arena example?

Thanks

**Comment by accdc** [comment]
Hi, no objections at all, please do.

The reason why I didn't include this in the AccDC Bootstrap module was the headache of mapping all data- attributes needed to configure the datagrid functionality using only HTML markup, but the setup.js file within the Coding Arena can easily be incorporated into whatever project you wish regardless even while using AccDC Bootstrap at the same time. This is true for all of the modules within the Coding Arena.

Kind regards,
Bryan

**Comment by mmikitka** [comment]
Thank you, Bryan
